In [1]:
import numpy as np
import pandas as pd

## Question 1

In [2]:
np.__version__

'1.19.2'

## Question 2

In [3]:
pd.__version__

'1.1.3'

In [6]:
!pip install wget

  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9686 sha256=84ec093bcbbe3b0cfce214bb0b410e7bfd00914bbfecd85d4afdba3eff3dc168
  Stored in directory: c:\users\yashaswy\appdata\local\pip\cache\wheels\bd\a8\c3\3cf2c14a1837a4e04bd98631724e81f33f462d86a1d895fae0
Successfully built wget


In [8]:
!python -m wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv


Saved under data.csv


In [9]:
df = pd.read_csv('data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

## Question 3 

In [19]:
bmw = df.groupby(['Make'])['MSRP'].mean()

In [20]:
bmw.head()

Make
Acura            34887.587302
Alfa Romeo       61600.000000
Aston Martin    197910.376344
Audi             53452.112805
BMW              61546.763473
Name: MSRP, dtype: float64

## Question 4

In [27]:
df_2015 = df[df['Year'] >= 2015]

In [31]:
df_2015.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

## Question 5

In [32]:
df_2015.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  5995.000000  5944.000000       5987.000000      5990.000000   
mean   2015.916264   272.987719          5.437281         3.600000   
std       0.795798   109.117257          1.718261         0.789774   
min    2015.000000    66.000000          0.000000         2.000000   
25%    2015.000000   184.000000          4.000000         4.000000   
50%    2016.000000   270.000000          6.000000         4.000000   
75%    2017.000000   325.000000          6.000000         4.000000   
max    2017.000000   750.000000         12.000000         4.000000   

       highway MPG     city mpg   Popularity           MSRP  
count  5995.000000  5995.000000  5995.000000    5995.000000  
mean     28.955129    21.526105  1758.674562   45667.156464  
std      10.088488    10.505942  1442.645543   40051.192137  
min      13.000000    10.000000    21.000000   11990.000000  
25%      24.000000    17.000000   640.000000   26910.000000  
50%      28.000000    20.000000  1439.000000   35845.000000  
75%      33.000000    24.000000  2031.000000   48105.000000  
max     354.000000   137.000000  5657.000000  548800.000000

In [34]:
df_2015['Engine HP'].fillna(int(df_2015['Engine HP'].mean()), inplace=True)

In [35]:
df_2015.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  5995.000000  5995.000000       5987.000000      5990.000000   
mean   2015.916264   272.979316          5.437281         3.600000   
std       0.795798   108.652091          1.718261         0.789774   
min    2015.000000    66.000000          0.000000         2.000000   
25%    2015.000000   184.000000          4.000000         4.000000   
50%    2016.000000   270.000000          6.000000         4.000000   
75%    2017.000000   325.000000          6.000000         4.000000   
max    2017.000000   750.000000         12.000000         4.000000   

       highway MPG     city mpg   Popularity           MSRP  
count  5995.000000  5995.000000  5995.000000    5995.000000  
mean     28.955129    21.526105  1758.674562   45667.156464  
std      10.088488    10.505942  1442.645543   40051.192137  
min      13.000000    10.000000    21.000000   11990.000000  
25%      24.000000    17.000000   640.000000   26910.000000  
50%      28.000000    20.000000  1439.000000   35845.000000  
75%      33.000000    24.000000  2031.000000   48105.000000  
max     354.000000   137.000000  5657.000000  548800.000000

## Question 6

In [41]:
rolls = df[df['Make']=='Rolls-Royce']
rolls = rolls[['Engine HP', 'Engine Cylinders', 'highway MPG']]
rolls = rolls.drop_duplicates()
rolls

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [42]:
X = rolls.to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [43]:
XT = X.T
XT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [51]:
XTX = XT.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [52]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [55]:
XTX_inv.sum()

0.032212320677486195

## Question 7

In [56]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
t = XTX_inv.dot(XT)

In [58]:
w = t.dot(y)
w[0]

0.19989598183186175